### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Shawnsdaddy** [MaaAssistantArknights/MaaCopilotServer#5]
- [ ] 修复下载逻辑。
- [ ] 新增(更新,删除)作业接口 （只有creater 或者是超管才可以更新或者删除）
- [ ] query返回content 里的干员
- [ ] 新增字段  **类别**（可以加入搜索，举例： 活动\主线\悖论模拟）
- [ ] 最好开放用户自行注册
- [ ] 用户登录返回权限

For future releases:
- [ ] 增加点赞逻辑。Limit: 每个人每个作业点赞一次（可以取消点赞）（没注册怎么点赞？）
- [ ] 开放普通用户注册？？
- [ ] 增加判定逻辑？？ 比如说上传相同关卡相同阵容可以忽略？

**Comment by LiamSho** [comment]
拆分 Issue
